---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.15.2
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# Air BNB Price Project


## Introduction


Lorem Ipsum  ahoaihsdoihasoisha

```{python}
import numpy as np
import pandas as pd
pd.set_option("mode.copy_on_write", True)
import scipy.stats as sps
import matplotlib.pyplot as plt
from pathlib import Path
from projtools import data_tools as dt
from projtools import plotting_tools as pt
```

## Prices

```{python}
from IPython.display import display, HTML
display(HTML("<style>.jp-OutputArea-output {display:flex}</style>"))
data = dt.data_setup()
property_data = dt.group_data(data,'property')
property_data.head()
```
# More Bedrooms - Higher Price?
According to [this 2023 article](https://www.rubyhome.com/blog/airbnb-stats/#airnb-hosts), there is a pretty stark correlation between how many bedrooms are listed in an airbnb and a higher price. Yet they combine every listing with 4 and more bedrooms into one - is there something else afoot?


```{python}
mean_price_per_bedroom = property_data.groupby(['bedrooms'])[['price_per_night_£']].mean()
mean_price_per_bedroom
```

Let's plot this out so we can see better:

```{python}
mean_price_per_bedroom.plot()
```

(insert analysis of graph above and of next steps (seeing sample size of each grouping) below)

```{python}
bedroom_counts = property_data['bedrooms'].value_counts()
bedroom_counts
```

more stuff about sample size and what constitutes a good sample - here we went for anything over 1000, as the rule is 10% of your sample size, if it does not exceed 1000 - ours did, so we went for 1000. and how graph below which only looks at bedrooms with at most 4

```{python}
mean_price_per_bedroom[:4].plot()
```

Conclusion - this looks pretty similar to the graph in the article! Let's do a linear regression on it:

```{python}
x = np.array([0, 1, 2, 3, 4])
y = np.array(mean_price_per_bedroom['price_per_night_£'][:4])
res = sps.linregress(x, y)
res
```

The interesting number here `rvalue = 0.92` as that implies a very positive correlation ... (write more here)

```{python}
plt.scatter(x, y)
plt.plot(x, res.intercept + res.slope*x, 'r', label='fitted line')
plt.show
```

# Price and Room Type

...(write stuff here)
Some of those one-bedrooms above are because the booker only has access to one room rather than the whole apartment. Could this be part of the reason why one-bedroom appartments have the lowest price on average, as people feel uncomfortable living with strangers?

```{python}
mean_price_per_room_type = property_data.groupby(['room_type'])[['price_per_night_£']].mean()
mean_price_per_room_type
```

Seems like a pretty sharp difference between some categories! Let's make sure we're not dealing with small sample sizes again though:

```{python}
room_type_counts = property_data['room_type'].value_counts()
room_type_counts
```

Neither Shared or Hotel rooms meet our standard of minimum 1000 values for a good sample size. So we'll only focus on Entire home/apt and Private rooms, and see whether there is a higher amount of 1 bedroom airbnbs in the latter, that could be influencing our above findings.

```{python}
bedrooms_per_room_type = property_data[property_data.room_type.isin(['Entire home/apt', 'Private room'])].groupby \
                    (['room_type'])[['bedrooms']]
bedrooms_per_room_type.value_counts()
```

While Private rooms overwhelmingly have only one bedroom, the Entire home/apt category also has that as its highest category. However we know from the value_counts above that there are 27479 Private rooms listed compared to 41217 Entire home/apt, so it could still have an influence on the price.

This is however where it gets tricky. 1 bedroom airbnbs prices lower because a sizeable chunk of them are Private rooms, or are Private rooms have a lower mean price because they mostly have 1 bedroom? This is where future studies utilising more qualitative methods such as surveys or focus groups may come in useful, asking both bookers and hosts why they price certain room and bedroom amounts in certain ways.


# The Must Haves

According to [Airbnb themselves](https://www.airbnb.com/resources/hosting-homes/a/the-amenities-guests-want-25) there are certain amenities that people really want to have in their airbnb. But does the price reflect that? Note that we will need to .dropna here for the .str.contains method to work, which may influence the end result.

The first most wanted amenity is a pool. This may be a stretch in London, so we'll combine that with number 5 on the list, a hot tub:

```{python}
property_data_dropna = property_data.dropna()
pool_tub_properties = property_data_dropna[property_data_dropna['amenities'].str.contains('hot tub|Hot tub|pool|Pool')]
len(pool_tub_properties)
```

This is well over our chosen minimum sample size. 

```{python}
property_data_dropna['Has Pool'] = property_data_dropna['amenities'].str.contains('hot tub|Hot tub|pool|Pool')
has_pool_grouped = property_data_dropna.groupby(['Has Pool'])[['price_per_night_£']].mean()
has_pool_grouped
```

Simply looking at the data we can see that there isn't much of a difference in price, and in fact, Airbnbs without a pool or a hot tub have a slightly higher average price per night than ones that do.

```{python}

```

#TO DO

Stats
Price per night by region  
Price per no. properties owned by hosts  
Price per review scores  
Number of properties owned by owners





Averages

```{python}

```
