---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.15.2
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

```{python}
from projtools import data_tools as dt
from projtools import plotting_tools as pt 
from projtools import quartile_prices as qp
from projtools import k_best_neighbours_prediction as k
from projtools import ttest_for_errors as ttest
data = dt.data_setup()

```

# Prediction model use

### Introduction


In the previous exploration of the AirBnb data two several issues where raised. The following notebook will look to provide a solution for a problem faced but each key stakeholder in the data - Airbnb, Hosts and Guests.

The problems are: 
 - A large number of hosts are violating the 90 night letting limit. Airbnb only have the avergae numebr of nights a room is booked for to go on to knwo if they are violating this or not, it can subsequently take a long time to establish whether these individuals are repeatadly going to violate the term or if they are likley to at any point.

 - Many hosts may have difficulty seetting an accurate price for there listing as it is nearly impossible to have complete market knowledge of the other similar properties.

 - As can be inferred from the previous pages some hosts ask for a lot higher pricing than other similar properties. Therefore, guests may find it difficult to identify whether they are being ripped off or not.



## Problem 1

A large number of hosts are violating the 90 night letting limit. Airbnb only have the avergae numebr of nights a room is booked for to go on to knwo if they are violating this or not, it can subsequently take a long time to establish whether these individuals are repeatadly going to violate the term or if they are likley to at any point.


In order to combat this issue we have created a model for use by Airbnb in order to identify those listing that have a high chance of beign let for over the 90 day limit.


The function does the following:

- Takes the ID of the new listing by a host
- It then standardises the results for the number of beedrooms, price of the property and the number of listings that the host has
- These values are then compared to the corresponding standardised values for a random sample of 1000 listings in the dataframe 
- The number of maximum avergae nights booked is then recorder for the the 2 most closely realated listings
- The mean average of these results is then taken to provide a prediction for the maximum average nights booked
- If the prediction is over the 90 day limit by at least 10 days (acting as an error buffer) then the fucntion will print "investigation needed" if not it will print "complies" to suggest that the host is not likely to let the property for over 90 days.

```{python}
# here is an example of the function in use
# The example ID 49698549 is a test for used to illusrate what the function would suggest.
# We know that the property in question does exceed the 90 day limit with a maximum nights average booking of 1125
k.ninety_day_test(49698549)
```

```{python}
# here is another example but for a property we know doesnt violate the 90 day limit with a maximum nights average booking of 10
k.ninety_day_test(39387)
```

```{python}
#  to see the code that maked up the function go to k_best_neighbours_prediction.py in projtools and look at the ninety_day_test_function
```

## Problem 2

Many hosts may have difficulty seetting an accurate price for there listing as it is nearly impossible to have complete market knowledge of the other similar properties.


In order to tackle this problem we created a function for use by hosts that provides a suggested price for their listing and then suggests whether they should increase or decrease their price based on other properties with certain similar characteristics chosen by the host.


The function does the following:

- Refines the data to the listings that are based in the same borough as the hosts listing
- Further refines the data to focus on the charactericts the host has chosen for price comparison dropping the listings that contain a NaN value 
- It then standardises the results for the three choosen variables
- 
These values are then compared to the corresponding standardised values for a random sample of 1000 listings in the datafra
- The prices of the five most similar listings are then averaged to provide a suggested price
- The difference is then calculated and depending on whether the suggested price is higher or lower than the price they currently have it it will suggest that they either decrease or increase the price of the listing
- The output will be this suggestion the suggested price and the current price of their listing

The inputs that the host needs to provide are:

- The three characteristics e.g number of beds, accomodates, review scores rating
- The ID of the listingme

```{python}
# The below shows what variables and example of what characteristics the host would choose and how they would assign them

ID_Z = 15400

var1 = 'accommodates'
var2 = 'number_of_reviews'
var3 = 'review_scores_rating'
```

```{python}
# here is an example of the function using the above characteristics that shows a property that is (slightly) overpriced comparatively

k.prediction_func_Hosts(var1, var2, var3, ID_Z)
```

```{python}
# Here is an example of the function using the above characteristics that shows a property that is (slightly) underpriced comparatively
# It uses different characteristics to show the flexibilty of the model 

ID_Z = 13913

var1 = 'review_scores_cleanliness'
var2 = 'bedrooms'
var3 = 'reviews_per_month'

k.prediction_func_Hosts(var1, var2, var3, ID_Z)
```

```{python}
# to see the code that maked up the function go to k_best_neighbours_prediction.py in projtools and look at the prediction_func_Hosts
```

## Problem 3

As can be inferred from the previous pages some hosts ask for a lot higher pricing than other similar properties. Therefore, guests may find it difficult to identify whether they are being ripped off or not.


To overcome this issue we have created a function that will let the guest know whether the listing they are considering is significantly overpriced, reasonabel or underpriced based on the chosen characteristics it has and the sigificance level chosen.


The function does the following:

- Refines the data to the listings that are based in the same borough as the lsiitng in question
- Further refines the data to focus on the charactericts the host has chosen for price comparison dropping the listings that contain a NaN value 
- It then standardises the results for the three choosen variables
- These values are then compared to the corresponding standardised values for a random sample of 1000 listings in the dataframe
- The prices of the five most similar listings are then averaged to provide a predicted price for that property given its charcateristics
- The difference is then calculated between the actual price and the predicted price
- A simple ttest is then done using this result and the error scores for x number of random rows in the data to test the significance of the actual price and the predicted price
- The significance level is decided by the guest to allow them to set there own boundaries for how much variation between the deviation in the predicted price and the actual price of the property they are intersted in and the equivalent deviation for the other properties that they are okay with before they consider the property that they are interested in to be a rip off.
- Based on whether the likelihood of getting the deviation result of their chosen listing is greater than or less than their chosen significance level for either the fucntion will state "Overpriced"

The inputs that the guest needs to provide are:

- The ID of the listing they want to investigate
- The three characteristics e.g accomomodates, number of reviews, review scores rating
- The significance level
- The number of rows for deviation comparison (the greater the number the more accurate but the function is)

```{python}
# here is an example of the funciion for a particular listing

ID_Z = 15400

var1 = 'accommodates'
var2 = 'number_of_reviews'
var3 = 'review_scores_rating'
significance = 0.99
rows = 10

ttest.overprice_function(var1, var2, var3, ID_Z, rows, significance)
```

```{python}
ID_Z = 15400

var1 = 'accommodates'
var2 = 'number_of_reviews'
var3 = 'review_scores_rating'
significance = 0.001
rows = 100

ttest.overprice_function(var1, var2, var3, ID_Z, rows, significance)
```

```{python}
# to see the code that maked up the function go to k_best_neighbours_prediction.py in projtools and look at the prediction_func_location function
# then go to ttest_for_errors.py in the same folder and look at overprice_function
```

```{python}
ID_Z = 15400

var1 = 'accommodates'
var2 = 'number_of_reviews'
var3 = 'review_scores_rating'

significance = 0.99
rows = 10

ttest.ttest_function(var1, var2, var3, 'price_per_night_£', ID_Z, rows)
```

```{python}
ID_Z = 15400

var1 = 'accommodates'
var2 = 'number_of_reviews'
var3 = 'review_scores_rating'

significance = 0.99
rows = 10

ttest.overprice_function_1(var1, var2, var3, ID_Z, rows, significance)
```

```{python}

```

```{python}

```

```{python}

```

```{python}

```

```{python}

```

```{python}

```

```{python}

```
